var MD_READER_STYLES = [
  '.md-reader-panel {',
  '  --wm-bg: #fbfaf7;',
  '  --wm-surface: #fffdf8;',
  '  --wm-surface-soft: #f4eee6;',
  '  --wm-text: #241f1a;',
  '  --wm-text-secondary: #5f574f;',
  '  --wm-text-muted: #8b8278;',
  '  --wm-border: #e6dccf;',
  '  --wm-hover: #f2eadf;',
  '  --wm-accent: #a86a43;',
  '  --wm-accent-hover: #8f5634;',
  '  --wm-accent-soft: #ead7c6;',
  '  --wm-shadow: rgba(36, 31, 26, 0.12);',
  '}',

  '.md-reader-panel {',
  '  position: fixed;',
  '  top: 0;',
  '  right: 0;',
  '  width: min(480px, 90vw);',
  '  min-width: 400px;',
  '  max-width: 70vw;',
  '  height: 100vh;',
  '  background: var(--wm-surface);',
  '  color: var(--wm-text);',
  '  z-index: 2147483647;',
  '  box-shadow: -8px 0 24px var(--wm-shadow);',
  '  display: flex;',
  '  flex-direction: column;',
  '  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;',
  '  animation: mdReaderSlideIn 180ms ease-out;',
  '}',

  '.md-reader-hidden {',
  '  display: none !important;',
  '}',

  '@keyframes mdReaderSlideIn {',
  '  from { transform: translateX(24px); opacity: 0; }',
  '  to { transform: translateX(0); opacity: 1; }',
  '}',

  '.md-reader-header {',
  '  height: 48px;',
  '  padding: 0 12px 0 16px;',
  '  border-bottom: 1px solid var(--wm-border);',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: space-between;',
  '  flex: none;',
  '}',

  '.md-reader-brand {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  gap: 8px;',
  '  min-width: 0;',
  '  flex-wrap: nowrap;',
  '}',

  '.md-reader-brand-mark {',
  '  width: 20px;',
  '  height: 20px;',
  '  border-radius: 6px;',
  '  background: #5b4dff;',
  '  display: grid;',
  '  place-content: center;',
  '  gap: 2px;',
  '  flex: none;',
  '}',

  '.md-reader-brand-mark span {',
  '  display: block;',
  '  width: 9px;',
  '  height: 2px;',
  '  border-radius: 999px;',
  '  background: #f3f0ff;',
  '}',

  '.md-reader-brand-mark span:last-child {',
  '  width: 6px;',
  '}',

  '.md-reader-title {',
  '  font-family: "Space Grotesk", Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;',
  '  font-weight: 700;',
  '  font-size: 14px;',
  '  letter-spacing: 0;',
  '}',

  '.md-reader-title-wow {',
  '  color: #5b4dff;',
  '}',

  '.md-reader-title-md {',
  '  color: var(--wm-text);',
  '  font-weight: 500;',
  '}',

  '.md-reader-version {',
  '  height: 20px;',
  '  display: inline-flex;',
  '  align-items: center;',
  '  padding: 0 6px;',
  '  border: 1px solid var(--wm-border);',
  '  border-radius: 999px;',
  '  color: var(--wm-text-muted);',
  '  background: var(--wm-surface-soft);',
  '  font-size: 11px;',
  '  font-weight: 700;',
  '  line-height: 1;',
  '  letter-spacing: 0;',
  '}',

  '.md-reader-close {',
  '  border: 0;',
  '  background: transparent;',
  '  cursor: pointer;',
  '  font-size: 16px;',
  '  color: var(--wm-text-secondary);',
  '}',

  '.md-reader-tabs {',
  '  display: flex;',
  '  border-bottom: 1px solid var(--wm-border);',
  '  flex: none;',
  '}',

  '.md-reader-tab {',
  '  flex: 1;',
  '  height: 40px;',
  '  border: 0;',
  '  background: var(--wm-surface-soft);',
  '  cursor: pointer;',
  '  font-size: 14px;',
  '  font-weight: 400;',
  '  color: var(--wm-text-muted);',
  '}',

  '.md-reader-tab.active {',
  '  background: var(--wm-surface);',
  '  color: var(--wm-text);',
  '  font-weight: 600;',
  '  border-bottom: 2px solid var(--wm-accent);',
  '}',

  '.md-reader-body {',
  '  flex: 1;',
  '  min-height: 0;',
  '  overflow: auto;',
  '}',

  '.hidden {',
  '  display: none !important;',
  '}',

  '.md-reader-toc-view {',
  '  padding: 16px;',
  '}',

  '.md-reader-status {',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  height: 200px;',
  '}',

  '.md-reader-loading {',
  '  color: var(--wm-text-secondary);',
  '  font-size: 14px;',
  '}',

  '.md-reader-error {',
  '  padding: 24px 16px;',
  '  text-align: center;',
  '}',

  '.md-reader-error-title {',
  '  font-size: 16px;',
  '  font-weight: 600;',
  '  color: var(--wm-text);',
  '  margin: 0 0 8px;',
  '}',

  '.md-reader-error-body {',
  '  font-size: 14px;',
  '  color: var(--wm-text-secondary);',
  '  margin: 0 0 16px;',
  '  line-height: 1.5;',
  '}',

  '.md-reader-retry-btn {',
  '  display: inline-block;',
  '  padding: 6px 16px;',
  '  border: 1px solid var(--wm-border);',
  '  border-radius: 8px;',
  '  background: var(--wm-surface-soft);',
  '  cursor: pointer;',
  '  font-size: 14px;',
  '  font-weight: 600;',
  '  color: var(--wm-text);',
  '}',

  '.md-reader-retry-btn:hover {',
  '  background: var(--wm-hover);',
  '}',

  '.md-reader-empty-toc {',
  '  color: var(--wm-text-muted);',
  '  font-size: 14px;',
  '  line-height: 1.6;',
  '}',

  '.md-reader-empty-toc p {',
  '  margin: 0 0 8px;',
  '}',

  '.toc-meta {',
  '  margin: 0 0 12px;',
  '  color: var(--wm-text-muted);',
  '  font-size: 13px;',
  '  font-weight: 500;',
  '}',

  '.toc-list {',
  '  display: flex;',
  '  flex-direction: column;',
  '  gap: 4px;',
  '}',

  '.toc-item {',
  '  width: 100%;',
  '  min-height: 32px;',
  '  display: flex;',
  '  align-items: center;',
  '  border: 0;',
  '  background: transparent;',
  '  text-align: left;',
  '  cursor: pointer;',
  '  padding: 4px 8px;',
  '  border-radius: 6px;',
  '  transition: background-color 120ms ease, color 120ms ease;',
  '  white-space: nowrap;',
  '  overflow: hidden;',
  '  text-overflow: ellipsis;',
  '}',

  '.toc-item:hover {',
  '  background: var(--wm-hover);',
  '}',

  '.toc-level-1 {',
  '  padding-left: 8px;',
  '  font-size: 14px;',
  '  font-weight: 600;',
  '  color: var(--wm-text);',
  '  line-height: 20px;',
  '  position: relative;',
  '}',

  '.toc-level-1::before {',
  '  content: "";',
  '  position: absolute;',
  '  left: 0;',
  '  top: 50%;',
  '  transform: translateY(-50%);',
  '  width: 3px;',
  '  height: 20px;',
  '  border-radius: 2px;',
  '  background: var(--wm-accent);',
  '  flex: none;',
  '}',

  '.toc-level-2 {',
  '  padding-left: 20px;',
  '  font-size: 13px;',
  '  font-weight: 500;',
  '  color: var(--wm-text-secondary);',
  '  line-height: 18px;',
  '}',

  '.toc-level-3 {',
  '  padding-left: 32px;',
  '  font-size: 12px;',
  '  font-weight: 400;',
  '  color: var(--wm-text-muted);',
  '  line-height: 18px;',
  '}',

  '.toc-level-4 {',
  '  padding-left: 44px;',
  '  font-size: 12px;',
  '  font-weight: 400;',
  '  color: var(--wm-text-muted);',
  '}',

  '.toc-level-5 {',
  '  padding-left: 56px;',
  '  font-size: 12px;',
  '  font-weight: 400;',
  '  color: var(--wm-text-muted);',
  '}',

  '.toc-level-6 {',
  '  padding-left: 68px;',
  '  font-size: 12px;',
  '  font-weight: 400;',
  '  color: var(--wm-text-muted);',
  '}',

  '.md-reader-read-view {',
  '  padding: 20px;',
  '  line-height: 1.6;',
  '  font-size: 14px;',
  '}',

  '.md-reader-back-link {',
  '  border: 0;',
  '  background: transparent;',
  '  color: var(--wm-accent);',
  '  cursor: pointer;',
  '  font-size: 13px;',
  '  font-weight: 600;',
  '  padding: 0;',
  '  margin: 0 0 14px;',
  '}',

  '.md-reader-back-link:hover {',
  '  text-decoration: underline;',
  '}',

  '.md-reader-read-content {',
  '  min-width: 0;',
  '}',

  '.md-reader-read-view h1,',
  '.md-reader-read-view h2,',
  '.md-reader-read-view h3,',
  '.md-reader-read-view h4,',
  '.md-reader-read-view h5,',
  '.md-reader-read-view h6 {',
  '  margin-top: 1.6em;',
  '  margin-bottom: 0.7em;',
  '  line-height: 1.25;',
  '}',

  '.md-reader-read-view h1 {',
  '  font-size: 24px;',
  '  border-bottom: 1px solid var(--wm-border);',
  '  padding-bottom: 0.3em;',
  '}',

  '.md-reader-read-view h2 {',
  '  font-size: 20px;',
  '  border-bottom: 1px solid var(--wm-border);',
  '  padding-bottom: 0.3em;',
  '}',

  '.md-reader-read-view h3 {',
  '  font-size: 17px;',
  '}',

  '.md-reader-read-view p {',
  '  margin: 0 0 12px;',
  '}',

  '.md-reader-read-view blockquote {',
  '  margin: 12px 0;',
  '  padding: 0 12px;',
  '  color: var(--wm-text-secondary);',
  '  border-left: 4px solid var(--wm-border);',
  '}',

  '.md-reader-read-view a {',
  '  color: var(--wm-accent-hover);',
  '  text-decoration: underline;',
  '  text-underline-offset: 2px;',
  '}',

  '.md-reader-read-view a:hover {',
  '  color: var(--wm-accent);',
  '}',

  '.md-reader-read-view pre {',
  '  overflow: auto;',
  '  padding: 12px;',
  '  border-radius: 8px;',
  '  background: var(--wm-surface-soft);',
  '}',

  '.md-reader-read-view code {',
  '  font-family: ui-monospace, SFMono-Regular, SFMono, Consolas, "Liberation Mono", Menlo, monospace;',
  '  font-size: 12px;',
  '}',

  '.md-table-wrap {',
  '  overflow-x: auto;',
  '  margin: 12px 0;',
  '}',

  '.md-reader-read-view table {',
  '  border-collapse: collapse;',
  '  width: max-content;',
  '  min-width: 100%;',
  '}',

  '.md-reader-read-view th,',
  '.md-reader-read-view td {',
  '  border: 1px solid var(--wm-border);',
  '  padding: 6px 8px;',
  '}',

  '.md-reader-read-view th {',
  '  background: var(--wm-surface-soft);',
  '}',

  '.md-reader-read-view img {',
  '  max-width: 100%;',
  '  height: auto;',
  '  border-radius: 6px;',
  '}',

  '.md-reader-footer {',
  '  flex: none;',
  '  padding: 12px;',
  '  border-top: 1px solid var(--wm-border);',
  '  display: flex;',
  '  flex-direction: column;',
  '  gap: 8px;',
  '}',

  '.md-reader-full-btn {',
  '  width: 100%;',
  '  height: 36px;',
  '  border: 1px solid var(--wm-border);',
  '  border-radius: 8px;',
  '  background: var(--wm-surface);',
  '  color: var(--wm-text);',
  '  cursor: pointer;',
  '  font-size: 13px;',
  '  font-weight: 700;',
  '}',

  '.md-reader-full-btn:hover:not(:disabled) {',
  '  background: var(--wm-hover);',
  '}',

  '.md-reader-full-btn:disabled {',
  '  cursor: not-allowed;',
  '  color: var(--wm-text-muted);',
  '  background: var(--wm-surface-soft);',
  '}',

  '.md-reader-site-link {',
  '  display: inline-flex;',
  '  align-self: center;',
  '  text-align: center;',
  '  color: var(--wm-text-muted);',
  '  font-size: 12px;',
  '  font-weight: 700;',
  '  text-decoration: none;',
  '  text-underline-offset: 3px;',
  '}',

  '.md-reader-site-link:hover {',
  '  color: var(--wm-accent-hover);',
  '  text-decoration: underline;',
  '}',

  '.md-section-content.collapsed {',
  '  display: none;',
  '}',

  '.md-fold-btn {',
  '  margin-left: 8px;',
  '  border: 0;',
  '  background: transparent;',
  '  cursor: pointer;',
  '  font-size: 13px;',
  '  color: var(--wm-text-secondary);',
  '}',

  '.md-fold-btn:hover {',
  '  color: var(--wm-text);',
  '}'
].join('\n');
